package com.inorder.clinical.acs.model;

public enum RecommendationType {
    PRIMARY_PCI,
    FIBRINOLYSIS_PHARMACOINVASIVE_PCI,
    EARLY_INVASIVE_CAG,
    LOW_INTERMEDIATE_MEDICAL_OPTIMISATION,
    DELAYED_ELECTIVE_CAG,
    PCI,
    CABG,
    PHYSIOLOGY_OR_STRESS_IMAGING,
    MEDICAL_THERAPY,
    VIABILITY_ASSESSMENT,
    CAG_PCI_IF_VIABLE,
    GDMT_ICD_CRT_CONSIDERATION
}
